### ISSUE TITLE
[Feature] Schematics

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/ngx-ytd-api#37]
There should be support for schematics to simplify the process of initialising the library.

# TODO

- [x] Read up on how to create a schematic (the Angular blog has a great [post](https://blog.angular.io/schematics-an-introduction-dc1dfbc2a2b2) on this very topic)
- [x] Initial installation schematic
  - [x] Fix issues with schematic testing
  - [ ] Add support for specifying default API key to be used (with the `NGX_YTD_API_STANDARD_PARAMS` injection token)
- [ ] Initial upgrade schematic (for upgrading to the [recently announced](https://blog.angular.io/version-7-of-angular-cli-prompts-virtual-scroll-drag-and-drop-and-more-c594e22e7b8c) Angular v7)
- [ ] Initial schematics for the Comments API
- [ ] Initial schematics for the Search API
- [ ] Initial schematics for the Videos API
- [ ] Initial upgrade schematics for potential future breaking changes
